* ONETAG: (anki menu item)

** what we want to do

it turns out that Anki opens files in a way that won't allow a
pipeline (as far as i can see), so the file itself needs to have the
tags in it.  or, maybe /dev/fdN could be used?

want a function that, given an argument, will ensure that 1) the
current deck has only cards with TAG; 2) all cards in Anki with TAG
are in that deck.

so, first, find all cards *not* in the current deck with TAG.  then,
move all those cards from their previous deck to the current deck.

XXX should we check we're not moving *too* many cards?

then, search the current deck and find all cards that do *not* have
the the designated tag.  delete all those cards.

XXX same, should we check we're not deleting too many cards?

remove the menu item (or, at least, the pre-canned tag)

after all this, *delete* the tags from all cards in the current
deck.

ANKI-IMPORT: (shell command)
usage: run the import operation, which cons up TAG, and adds it to
all the cards in the deck, then imports the cards into the named
deck: ./anki-import turkish-2015 turkish-2015.html after the import,
prime a menu item in Anki (with a shortcut, hopefully), that will
cause onetag to run with the correct tag.

one function: given a file name and a deck name, import the contents
of that file into that deck.  need to have it tell how many fields
it will find (maybe separate function for that?).

one function: given a search expression (such as "deck:current
tag:fubar"), execute the search, and then execute a "move" to a
designated deck (which must already exist).

one function: given a search expression, execute the search and
print out the resulting cards.

one function: print the names of the existing decks.

one function: remove a given tag from a given (all?) deck(s?).

to get anki to work, need to run ./tools/build-ui.sh.  for *that*,
needed something from Qt designer, which required installing a bunch
of Qt.  then, to actually run it, needed to extend path, which i did
by
#+BEGIN_EXAMPLE
bash
PATH=/sw/lib/qt4-mac/lib/python2.7/bin/:$PATH
./tools/build_ui.sh 
#+END_EXAMPLE
then, needed to copy all the files to ~/usr/lib/python/anki/ again
(i.e., *after* running ./tools/build-ui.sh).

cool.  now have an x11 version of anki ("% ./runanki").

** some code
#+name: anki2
| /Users/minshall/Documents/Anki/User 1/collection.anki2 |
#+name: deck
| testdeck |
#+name: imfile
| /Users/minshall/src/mine/ankiplugins/test.html |


#+BEGIN_SRC python :var a=deck[0,0] :results results raw :session ss
#+END_SRC

#+RESULTS:
testdeck

#+name: collection_guard
#+BEGIN_SRC python :session ss
  # http://effbot.org/zone/python-with-statement.htm
  class collection_guard:
      def __init__(self, ankipath):
          self.ankipath = ankipath;
      def __enter__(self):
          self.col = Collection(ankipath);
          return self;
      def __exit__(self, type, value, traceback):
          self.col.close();
          self.col = None
          return False
      def close(self):
          self.__exit__(None, None, None)
#+END_SRC

#+RESULTS: collection_guard



#+name: decks
#+BEGIN_SRC python :var ankipath=anki2[0,0] :results output :session ss
  from anki import Collection

  def pdecks(col):
      for i, val in enumerate(col.decks.allNames()):
          print val

  def pdecksrun():
      with collection_guard(ankipath) as cg:
          pdecks(cg.col)

  pdecksrun();
#+END_SRC

#+RESULTS: decks
: 
: >>> >>> ... ... ... >>> ... ... ... >>> Custom Study Session
: osmanlica-2015
: testdeck
: turkish-2014
: Default
: turkish-2015
: ImportDeck

#+name: notes
#+BEGIN_SRC python :results output :var ankipath=anki2[0,0] deck=deck[0,0] :session ss
  from anki import Collection

  def pnotes(col):
      ids = col.findNotes("deck:%s" % deck)
      for i, id in enumerate(ids):
          note = col.getNote(id)
          values = note.values();
          print "%s\t%s" % (values[0], values[1])

  def pnotesrun():
      with collection_guard(ankipath) as cg:
          pnotes(cg.col)

  pnotesrun();
#+END_SRC

#+RESULTS: notes

#+name: tags
#+BEGIN_SRC python :results output :var anki=anki2[0,0] deck=deck[0,0] :session ss
  from anki import Collection
  with collection_guard(ankipath) as cg:
      ids = cg.col.findCards("deck:%s" % deck)
#+END_SRC

#+RESULTS: tags

#+name: import
#+BEGIN_SRC python :session ss :results output :var ankipath=anki2[0,0] :var deckname=deck[0,0] :var imfile=imfile[0,0]
  from anki import Collection
  from anki.importing import TextImporter
  from anki.tags import TagManager

  def constag():
      import time;
      return "asof%d" % time.time();

  # get foreign notes: these aren't (yet) real Anki notes, just a
  # represenation that has been read in.
  def getfnotes(ti):
      # now, get the notes
      fnotes = ti.foreignNotes();
      return fnotes;

  def addtag(ti, fnotes, tag):
      for i, fn in enumerate(fnotes):
          fn.tags.append(tag)

  def add2col(col, deckname, ti, fnotes):
      # XXX should we remember previously selected deck (and reselect it
      # when we're done here)?
      did = col.decks.id(deckname)
      col.decks.select(did)
      ti.importNotes(fnotes)


  # http://ankisrs.net/docs/addons.html#the-database
  def run():
      tag = constag();            # just run once!
      col = Collection(ankipath)
      with collection_guard(ankipath) as col_guard:
          col = col_guard.col
          ti = TextImporter(col, imfile)
          # first, get anki read in the notes (to an intermediate form)
          fnotes = getfnotes(ti)
          # next, add our tag to the notes
          addtag(ti, fnotes, tag)
          # now, add these notes to the designated deck
          add2col(col, deckname, ti, fnotes)
          del ti;                 # no longer to be used
          # now, delete any notes in deck that do *not* have this tag
          delnontagged(col, tag, deckname)
          # now, move any notes from any *other* cards with this tag to this deck
          movetagged(col, tag, deckname)
          # now, delete this tag from these cards (no other cards should have this tag)
          # done!
#+END_SRC

#+RESULTS: import
: 
: >>>   File "<stdin>", line 1
:     import codecs, os;__pyfile = codecs.open('''/var/folders/qc/gxydc5q150qbr2mndftfyrmw0000gn/T/py149540Oy''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/qc/gxydc5q150qbr2mndftfyrmw0000gn/T/py149540Oy''');exec(compile(__code, import codecs, os;__pyfile = codecs.open('''/var/folders/qc/gxydc5q150qbr2mndanki="/Users/minshall/Documents/Anki/User 1/collection.anki2"
:                                                                                                                                                                                                                                                                                                            ^
: SyntaxError: invalid syntax

** some bugs maybe in dae's code/documentation

*** [[http://ankisrs.net/docs/addons.html][add-on documentation]] bugs

+ in "Import a text file into the collection"
#+BEGIN_QUOTE
deck['mid'] = m['id']
#+END_QUOTE
should possibly be
#+BEGIN_QUOTE
deck['mod'] = m['mod']
#+END_QUOTE
?

+ this is another
